--- #YAML:1.0
name:               AWS-S3
version:            0.023
abstract:           Lightweight interface to Amazon S3 (Simple Storage Service)
author:
    - John Drago <jdrago_999@yahoo.com>
license:            perl
distribution_type:  module
test_requires:
    Test::More:       0
requires:
    Carp:                       0
    Class::Load:                0
    Iterator::Paged:            1.001
    XML::LibXML:                0
    XML::LibXML::XPathContext:  0
    LWP::UserAgent::Determined: 0
    Digest::HMAC_SHA1:          0
    MIME::Base64:               0
    URI::Escape:                0
    VSO:                        0.022
    Iterator::Paged:            0
no_index:
    directory:
        - t
        - inc
generated_by:       Hand
resources:
    repository: git://github.com/jdrago999/AWS-S3.git
    homepage:  https://github.com/jdrago999/AWS-S3
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
