---
abstract: unknown
author:
  - 'Lee Johnson <leejo@cpan.org>'
build_requires:
  Test::Deep: '0.112'
  Test::More: '0.31'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AWS-S3
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Class::Load: '0'
  Digest::HMAC_SHA1: '0'
  HTTP::Date: '0'
  Iterator::Paged: '0'
  JSON::XS: '0'
  LWP::UserAgent::Determined: '0'
  MIME::Base64: '0'
  Moose: '2.0'
  MooseX::Types: '0'
  MooseX::Types::URI: '0'
  Test::Deep: '0'
  URI::Escape: '0'
  XML::LibXML: '0'
  XML::LibXML::XPathContext: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/leejo/AWS-S3/issues
  homepage: https://metacpan.org/module/AWS-S3
  license: http://dev.perl.org/licenses/
  repository: https://github.com/leejo/AWS-S3
version: '0.050'
